name: Create New Flow inside the cx dialogflow agent
on:
  workflow_dispatch:
jobs:
  build-and-restore:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout repo
      - name: Checkout
        uses: actions/checkout@v4
      # 2️⃣ Authenticate to GCP (Dev/Prod credentials)
      - name: Auth to GCP (Prod)
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      # 3️⃣ Install cxcli
      - name: Install cxcli
        run: |
          curl -L -o cxcli.tar.gz https://github.com/xavidop/dialogflow-cx-cli/releases/download/v1.239.0/cxcli_Linux_x86_64.tar.gz
          tar -xzf cxcli.tar.gz
          sudo mv cxcli /usr/local/bin/
          cxcli version

 
      # 4️⃣ Create new flow inside the agent
      - name: Create new flow
        run: |
          echo "Creating new flow..."
          cxcli flow create "GitFlow" \
          --agent-id "RogerDemo_Git2" \
          --project-id "roger-470808" \
          --location-id "us-central1" \
          --description "This is a new flow created via GitHub Actions" \
          --output-format json \
          --verbose
